/**
 * donors.ts — where model values come from.
 *
 * A "donor" is a list of models whose values can be copied onto ours, matched on
 * the BARE model name: the id with any `vendor/` prefix stripped on both sides,
 * so `deepseek-v4-flash` matches `deepseek/deepseek-v4-flash`. A prefix
 * relationship is not an identity: `glm-5.3` does not inherit from
 * `glm-5.3-flash`.
 *
 * ## One source, and it ships with Pi
 *
 * The donor is the catalog Pi bundles inside its own package:
 *
 *     pi-ai/dist/providers/data/<provider>.json
 *
 * There is no second donor list to maintain. The catalog is regenerated by Pi on
 * every update, covers 42 providers, and reading a file needs no credential —
 * a key is only needed to CALL an API, not to read what Pi installed.
 *
 *     openrouter  the primary donor. It is the largest model router in the world
 *                 and the catalog is its core business, so the numbers are kept
 *                 by people who cannot afford to be wrong.
 *     the rest    corroboration only. A provider lower in the order confirms the
 *                 model exists and agrees on its structure; it fills a field the
 *                 ones above left empty and never overrides.
 *
 * ## The order
 *
 *     the vendor's own model card  >  openrouter  >  the rest of Pi's catalogs
 *
 * **A donor that knows a field decides it.** That is the whole rule, and it is
 * the same one the EnClave bridge uses. It is why a probe against this gateway
 * can lose to openrouter: the catalog is maintained by people who route these
 * models for a living.
 *
 * **A donor that is SILENT about a field does not erase a known value.** That is
 * a different situation, not a competing opinion: nobody claimed anything about
 * it. Losing `mimo-v2.6-flash`'s seven reasoning levels to a catalog that lists
 * no levels at all would be data loss dressed as precedence. So a missing donor
 * field falls through to whatever we already know — the curated layer, or a
 * probe against this endpoint.
 *
 * Nothing is ever averaged. A number nobody published is not a consensus, it is
 * an invention.
 *
 * ## What no donor may set
 *
 *   contextWindow — the endpoint's own `metadata.context_limit` states what this
 *                   gateway actually serves.
 *   cost          — a donor's price is for a different reseller.
 *   compat        — `thinkingFormat` and friends describe how one particular
 *                   reseller wants reasoning framed. Amr-link has been verified
 *                   by sending `reasoning_effort` and watching what comes back.
 *
 * ## Router aliases are never resolved
 *
 * Amr-link's `/models` returns ids, not aliases, but the guard is kept so that a
 * catalog entry sharing a bare name with a pseudo-model can never overwrite it.
 */

import { readFileSync, readdirSync, realpathSync, statSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export type ThinkingLevel = "off" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
export type ThinkingLevelMap = Partial<Record<ThinkingLevel, string | null>>;

export interface ModelEntry {
  id: string;
  name?: string;
  api?: string;
  provider?: string;
  reasoning?: boolean;
  thinkingLevelMap?: ThinkingLevelMap;
  input?: Array<"text" | "image">;
  cost?: { input: number; output: number; cacheRead: number; cacheWrite: number };
  contextWindow?: number;
  maxTokens?: number;
  compat?: Record<string, unknown>;
  /**
   * Set by the sync script. `source` supplied the values; `corroborating`
   * lists the other providers that also know the model and agree it exists.
   */
  donor?: {
    /** The provider that supplied the values. */
    source: string;
    /**
     * The exact id that matched, WITH its prefix — `qwen/qwen3.8-max-0902`, not
     * `qwen3.8-max`. Matching is done on the bare name because the two sides
     * carry different vendor prefixes, but recording the full id is what makes a
     * match auditable: you can see which entry was taken, including when it came
     * from a dated slug.
     */
    matchedId?: string;
    /** Other catalogs that also know this model. They confirm, never override. */
    corroborating: string[];
    rule: "vendor" | "donated" | "kept" | "corroborated" | "none";
  };
  [key: string]: unknown;
}

/** Fields a bundled donor may contribute. `compat` is deliberately absent. */
export const BUNDLED_FIELDS = ["reasoning", "thinkingLevelMap", "input", "maxTokens"] as const;

/** Fields already written in models.json may contribute, `compat` included. */
export const HAND_FIELDS = [...BUNDLED_FIELDS, "compat"] as const;

/**
 * How close a hand-written value must be to a bundled one to count as the same
 * number. `128_000` vs `131_072` is 2.3%; `232_000` vs `384_000` is 66%.
 */
export const ROUNDING_TOLERANCE = 0.05;

export function bareName(id: string): string {
  const i = id.lastIndexOf("/");
  return i === -1 ? id : id.slice(i + 1);
}

/**
 * Reduce a model name to its letters and digits, lowercased.
 *
 * Two spellings of one model survive this: `deepseek-v4.1-flash` and
 * `DeepSeek V4.1 Flash` both become `deepseekv41flash`. That is how the
 * catalogs index a model by its human name — Pi's own vendor catalog writes
 * `id: "deepseek-flash"` with `name: "DeepSeek V4.1 Flash"`, so the endpoint's
 * id and that name are the same key once punctuation is gone.
 *
 * This is an exact match on a different field, not a similarity guess. That is
 * what keeps it safe: `deepseek-v4-flash` and `deepseek-v4-flash-0731` stay
 * apart because the date is in the name too, and `glm-5.3` never reaches
 * `glm-5.3-flash` because each catalog holds them under separate keys.
 */
export function normaliseModelKey(s: string): string {
  return s.toLowerCase().replace(/chat:/g, "").replace(/[^a-z0-9]+/g, "");
}

/**
 * Catalog file names that differ from the vendor slug an id carries.
 *
 * OpenRouter writes `z-ai/glm-5.3`; the catalog that speaks for the vendor is
 * `zai.json`. Without this the vendor's own catalog is never consulted and its
 * numbers lose to the reseller's.
 */
export const VENDOR_CATALOG_ALIASES: Record<string, string> = {
  "z-ai": "zai",
  "~z-ai": "zai",
  moonshot: "moonshotai",
  "deepseek-ai": "deepseek",
};

/**
 * Which catalog speaks for a model family: the vendor's own, never a reseller.
 *
 * This cannot be derived automatically. Every catalog stamps `provider` on its
 * entries, but a reseller stamps its OWN name — `opencode.json` says
 * `provider: opencode` on a `kimi-k3` it resells. What marks the real thing is
 * that the vendor's catalog lists the model under its bare name
 * (`kimi-k2.6`, `claude-fable-5`, `gpt-4`, `glm-5.2`, `mimo-v2.5`) while
 * resellers carry a `vendor/` prefix. So it is recorded here, one line per
 * family, the same way NAME_ALIASES records one fact per model.
 *
 * A model whose family is absent here has no vendor catalog to consult and
 * falls through to the corroboration rule. That is not a gap to paper over:
 * `qwen3.8-max` has no first-party catalog in Pi, and its levels are settled
 * by agreement among the others.
 */
export const FAMILY_VENDOR: Record<string, string> = {
  claude: "anthropic",
  gpt: "openai",
  o1: "openai",
  o3: "openai",
  o4: "openai",
  chatgpt: "openai",
  kimi: "moonshotai",
  deepseek: "deepseek",
  glm: "zai",
  chatglm: "zai",
  mimo: "xiaomi",
  minimax: "minimax",
  nemotron: "nvidia",
  mistral: "mistral",
  ministral: "mistral",
  magistral: "mistral",
};

/**
 * The family a model belongs to: the letters before its first digit.
 *
 * `kimi-k3` and `gpt-oss-120b` give `kimi` and `gpt`; `qwen3.8-max` gives
 * `qwen`, not `qwen3`, so a version bump cannot move a model out of its family.
 */
export function modelFamily(bare: string): string {
  const m = /^[a-z]+/i.exec(bare);
  return m ? m[0].toLowerCase() : "";
}

/** The vendor's own catalog for this model, if one of them knows it. */
export function vendorCatalogProvider(hits: readonly CatalogHit[], bare: string): string | undefined {
  const wanted = FAMILY_VENDOR[modelFamily(bare)];
  if (!wanted) return undefined;
  return hits.some((h) => h.provider === wanted) ? wanted : undefined;
}

/**
 * EnClave sells a model under a short name; a catalog lists the same weights
 * under the dated slug the vendor publishes. These are the same model, so the
 * dated slug is looked up when the short one finds nothing.
 *
 * Kept as data, not a rule: each line is a fact about one model, not a general
 * "strip the date" heuristic. Stripping dates automatically would be wrong —
 * `deepseek-v4-flash` and `deepseek-v4-flash-0731` are different checkpoints,
 * and so is `qwen3.8-max` from `qwen3.8-max-0902`.
 */
export const NAME_ALIASES: Record<string, readonly string[]> = {
  "qwen3.8-max": ["qwen3.8-max-0902"],
  "nemotron-ultra": ["nemotron-3-ultra-550b-a55b"],
};

function num(v: unknown): number | undefined {
  return typeof v === "number" && Number.isFinite(v) ? v : undefined;
}

// ---------------------------------------------------------------------------
// Where Pi keeps its bundled catalogs
// ---------------------------------------------------------------------------

/**
 * Find `pi-ai/dist/providers/data` without hardcoding the version.
 *
 * The directory is named `@earendil-works+pi-ai@<version>_<dependency hash>`,
 * so the hash changes on every Pi update and any stored path dies with it. It
 * sits under the pnpm store beneath the agent directory; this walks that store
 * rather than guessing a depth.
 */
export interface CatalogLocation {
  dir: string;
  /** Which copy this is, for the report. */
  origin: "pi install" | "global install";
}

/**
 * The catalogs sit in one of two shapes depending on how Pi was installed:
 *
 *   <pkg>/dist/providers/data     a compiled install: pnpm store or global
 *   <pkg>/providers/data          a flat install, straight under the agent
 *                                  directory, with no build step and no `dist`
 *
 * Both are checked. Insisting on one shape reports "no donor" on every layout
 * but its own, which is indistinguishable from the donors being broken.
 */
const CATALOG_SHAPES = [
  ["dist", "providers", "data"],
  ["providers", "data"],
] as const;

/** Takes a package DIRECTORY, not a package.json path. */
function catalogAt(pkgDir: string): string | undefined {
  for (const shape of CATALOG_SHAPES) {
    const candidate = join(pkgDir, ...shape);
    try {
      if (statSync(candidate).isDirectory()) return candidate;
    } catch {
      // try the next shape
    }
  }
  return undefined;
}

/**
 * Where the Pi package itself may live. Only used to resolve pi-ai.
 *
 * The prefix is derived from `process.execPath` rather than assumed: on Termux
 * it is `/data/data/com.termux/files/usr`, not `/usr`, so a hardcoded `/usr/lib`
 * silently never matches. Getting this wrong does not throw — it just sends the
 * lookup to the wrong copy of the catalog.
 */
function piPackageCandidates(): string[] {
  const out: string[] = [];
  const add = (base: string) => {
    const p = resolve(base, "@earendil-works", "pi-coding-agent");
    try {
      if (statSync(p).isDirectory()) out.push(p);
    } catch {
      // not here
    }
  };

  // The install this module lives under, when Pi loads it from its own bundle.
  add(dirname(fileURLToPath(import.meta.url)) + "/..");

  // The global prefix this node was installed under.
  try {
    add(dirname(dirname(process.execPath)) + "/lib/node_modules");
  } catch {
    // execPath unavailable
  }

  // Conventional prefixes, only used where they actually exist.
  add("/usr/local/lib/node_modules");
  add("/usr/lib/node_modules");

  return [...new Set(out)];
}

/**
 * Find Pi's bundled catalogs without depending on a version or a hash.
 *
 * The directory is named `@earendil-works+pi-ai@<version>_<dependency hash>`, so
 * any stored path dies on the next update. Only stable prefixes are used and the
 * tree is searched at run time.
 *
 * Order matters, because there can be more than one copy of pi-ai and reading
 * the wrong one fails silently:
 *
 *   1. ASK NODE. `createRequire` from Pi's own package resolves the exact pi-ai
 *      that Pi loads its models from. That is ground truth, not a guess.
 *   2. FALL BACK to the agent's pnpm store, which is where `pi install npm:…`
 *      puts things on this device. When several versions sit there, the one whose
 *      version matches Pi's package wins; otherwise the highest, never a `+` build.
 *
 * On this device step 1 currently fails: the global install of pi-ai is an empty
 * directory, so Pi resolves it from the agent's store. Both steps are kept
 * because either can be true after an update.
 */
export function findBundledCatalogs(agentDir: string): CatalogLocation[] {
  const found: CatalogLocation[] = [];
  const push = (dir: string | undefined, origin: CatalogLocation["origin"]) => {
    if (dir && !found.some((f) => f.dir === dir)) found.push({ dir, origin });
  };

  // Walking the tree by hand rather than using module resolution: pi-ai is
  // ESM-only with an `exports` map that exposes neither a main nor its own
  // package.json, so require.resolve fails on it with
  // ERR_PACKAGE_PATH_NOT_EXPORTED. The directory is right there next to Pi, so
  // looking for it directly is both simpler and immune to that.
  for (const piPkg of piPackageCandidates()) {
    push(catalogAt(join(piPkg, "node_modules", "@earendil-works", "pi-ai")), "la que usa Pi");
  }

  for (const dir of storeCatalogs(agentDir)) push(dir, "pi install");
  return found;
}

/**
 * Every usable copy in the agent's pnpm store, best first.
 *
 * When several versions sit there the newest wins, and a `+` build never does —
 * a prerelease is never the one a released Pi runs. Exported separately so the
 * preference order can be tested without the Pi install shadowing it.
 */
const storeCache = new Map<string, string[]>();

/** Cached because Pi refreshes on every /model search, and the tree under
 *  node_modules holds several hundred packages. The catalogs do not change
 *  while the process is alive. */
export function storeCatalogs(agentDir: string): string[] {
  const cached = storeCache.get(agentDir);
  if (cached) return cached;
  try {
    return storeCatalogsUnsafe(agentDir);
  } catch {
    // Unreadable tree, a broken junction, a path that is not a directory: the
    // honest answer is "no catalogs found", not an exception.
    storeCache.set(agentDir, []);
    return [];
  }
}

function storeCatalogsUnsafe(agentDir: string): string[] {
  const roots = agentRoots(agentDir);
  const out: string[] = [];
  const seen = new Set<string>();

  const visit = (pkgDir: string, depth: number) => {
    if (depth > 2) return;
    const dir = catalogAt(pkgDir);
    let count = 0;
    try {
      count = dir ? readdirSync(dir).filter((f) => f.endsWith(".json")).length : 0;
    } catch {
      count = 0;
    }
    if (dir && count) {
      // Dedupe by real path: the pnpm store links the same copy under many
      // entry folders, and counting it ten times hides which one is live.
      let key = dir;
      try {
        key = realpathSync(dir);
      } catch {
        /* not a link */
      }
      if (!seen.has(key)) {
        seen.add(key);
        out.push(dir);
      }
    }
    // Descend two ways, because the layout depends on where Pi was installed.
    //
    //   node_modules/<pkg>/node_modules/@scope/<pkg>     a plain install
    //   <store>/@scope+name@version_hash/node_modules/…    a pnpm store
    //
    // In the pnpm case the store entries sit DIRECTLY under the root, not under
    // a node_modules, so a walk that only looks at `node_modules` finds nothing.
    // That is the whole bug: a store whose folder is named after a different
    // package than the one holding the catalogs was skipped entirely.
    const nm = join(pkgDir, "node_modules");
    let scopes: string[] = [];
    try {
      scopes = readdirSync(nm);
    } catch {
      scopes = [];
    }
    for (const scope of scopes) {
      if (scope.startsWith("@")) {
        let pkgs: string[] = [];
        try {
          pkgs = readdirSync(join(nm, scope));
        } catch {
          continue;
        }
        for (const pkg of pkgs) visit(join(nm, scope, pkg), depth + 1);
      } else {
        visit(join(nm, scope), depth + 1);
      }
    }

    // Directly under a root there are two kinds of child worth visiting:
    // pnpm store entries (`@scope+name@version_hash`) and, in a flat install,
    // the packages themselves hanging off a scope (`@earendil-works/pi-ai`).
    // The second has no `+` and no `@` in its own name, so a filter that only
    // accepted store entries skipped every flat install — which is why a layout
    // with the catalogs under `node_modules/@earendil-works/pi-ai/providers`
    // came back empty.
    if (depth === 0) {
      let entries: string[] = [];
      try {
        entries = readdirSync(pkgDir);
      } catch {
        entries = [];
      }
      for (const entry of entries) {
        // A pnpm store entry is `@scope+name@version_hash`. It BOTH starts with
        // `@` and contains `+`, so it has to be tested for `+` first — matching it
        // as a scope directory instead would visit it as an empty scope and skip
        // the very copy we are looking for.
        if (entry.includes("+")) {
          const full = join(pkgDir, entry);
          try {
            if (statSync(full).isDirectory()) visit(full, depth + 1);
          } catch {
            // not a directory
          }
          continue;
        }
        if (entry.startsWith("@")) {
          const scopeDir = join(pkgDir, entry);
          try {
            for (const pkg of readdirSync(scopeDir)) {
              const full = join(scopeDir, pkg);
              if (statSync(full).isDirectory()) visit(full, depth + 1);
            }
          } catch {
            // unreadable scope
          }
          continue;
        }
        const full = join(pkgDir, entry);
        try {
          if (!statSync(full).isDirectory()) continue;
        } catch {
          continue;
        }
        visit(full, depth + 1);
      }
    }
  };

  for (const root of roots) {
    let ok = false;
    try {
      ok = statSync(root).isDirectory();
    } catch {
      ok = false;
    }
    if (ok) visit(root, 0);
  }

  // Highest version first, so if two copies survive, the newer one is used.
  const sorted = out.sort((a, b) => versionAt(b) - versionAt(a));
  storeCache.set(agentDir, sorted);
  return sorted;
}

/** Best-effort major.minor.patch out of a `.../node_modules/<pkg>` path. */
function versionAt(dir: string): number {
  // A store folder is `name@version_hash`, and the name is itself often
  // `@scope+pkg`. So the version is only what follows the LAST `@` — matching
  // the `+` of a scope instead would mark every folder a prerelease.
  // The path contains `/node_modules/` twice — once in `npm/node_modules/.pnpm`
  // and once inside the store entry — so splitting on the first occurrence
  // yields "npm" and no version at all. Take the store entry explicitly.
  // Windows uses `\`, so normalise before splitting.
  const parts = dir.replace(/\\/g, "/").split("/");
  const pnpmAt = parts.lastIndexOf(".pnpm");
  const dataAt = parts.lastIndexOf("data");
  const folder = (pnpmAt !== -1 && parts[pnpmAt + 1]) || (dataAt > 1 && parts[dataAt - 1]) || "";
  const lastAt = folder.lastIndexOf("@");
  if (lastAt === -1) return -1;
  const version = folder.slice(lastAt + 1).split("_")[0];
  // A `+build` version is a prerelease, never the copy a released Pi runs.
  if (version.includes("+")) return -1;
  const m = /^(\d+)\.(\d+)\.(\d+)/.exec(version);
  if (!m) return -1;
  return Number(m[1]) * 1e6 + Number(m[2]) * 1e3 + Number(m[3]);
}

/**
 * Every directory that could hold a pnpm-style store.
 *
 * `agentDir` is normally correct — Pi's own `getAgentDir()` follows
 * PI_CODING_AGENT_DIR, so a launcher that relocates the agent directory is
 * handled for us. The siblings are belt and braces for the case where the
 * extension runs under one agent dir while the catalogs were installed under
 * another, which is what a shell wrapper like gentle-shell produces.
 */
export function agentRoots(agentDir: string): string[] {
  // The real home, NOT dirname(agentDir): with agentDir = ~/.pi/agent that
  // yields ~/.pi, and joining ".pi/agent" onto it gives the nonsense ~/.pi/.pi/agent.
  const home = homedir();
  // Deduplicated: with agentDir = ~/.pi/agent the first and third entries are
  // the same path, and scanning it twice doubled the cost for nothing.
  return [...new Set([
    // The pnpm stores, where the folder is renamed per version and hash.
    join(agentDir, "npm", "node_modules", ".pnpm"),
    join(home, ".gentle-shell", "agent", "npm", "node_modules", ".pnpm"),
    join(home, ".pi", "agent", "npm", "node_modules", ".pnpm"),
    // A flat install, straight under the agent directory, not renamed and with
    // no build step. This is the shape teams installing Pi directly get. It is
    // a much larger tree than a store, so it is only walked if no store was
    // found.
    join(agentDir, "npm", "node_modules"),
    join(home, ".gentle-shell", "agent", "npm", "node_modules"),
  ])];
}

/** Pi's own version, for the report only. Note this is NOT pi-ai's version:
 *  the two use independent numbering (1.0.0 vs 0.85.1), so they never match and
 *  must not be compared. */
export function piPackageVersion(): string | undefined {
  for (const piPkg of piPackageCandidates()) {
    try {
      const pkg = JSON.parse(readFileSync(join(piPkg, "package.json"), "utf8")) as { version?: string };
      if (pkg.version) return pkg.version;
    } catch {
      // try the next
    }
  }
  return undefined;
}

/** Numeric dotted comparison, so 0.9 sorts below 0.10. */
function compareVersions(a: string, b: string): number {
  const pa = a.split(".").map((n) => Number(n) || 0);
  const pb = b.split(".").map((n) => Number(n) || 0);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const d = (pa[i] ?? 0) - (pb[i] ?? 0);
    if (d) return d;
  }
  return 0;
}

/** The catalogs to read, best location first. Never throws. */
export function findBundledCatalogDir(agentDir: string): string | undefined {
  return findBundledCatalogs(agentDir)[0]?.dir;
}

/** Provider ids that have a credential in `auth.json`. */
export function activeProviders(agentDir: string): Set<string> {
  try {
    const auth = JSON.parse(readFileSync(join(agentDir, "auth.json"), "utf8")) as Record<string, unknown>;
    return new Set(Object.keys(auth));
  } catch {
    return new Set();
  }
}

export interface BundledCatalog {
  provider: string;
  /** bare name -> entry */
  models: Map<string, ModelEntry>;
  /**
   * Human name, punctuation-stripped -> entry. Optional so a catalog built by
   * hand (in tests, or by an older caller) still works; lookups fall back to
   * `models` when it is absent.
   */
  modelsByName?: Map<string, ModelEntry>;
}

/** Read one bundled catalog. The JSON is keyed by API, then by model id. */
export function readBundledCatalog(
  catalogDir: string,
  provider: string,
): BundledCatalog | undefined {
  let raw: Record<string, Record<string, ModelEntry>>;
  try {
    raw = JSON.parse(readFileSync(join(catalogDir, `${provider}.json`), "utf8"));
  } catch {
    return undefined;
  }
  const models = new Map<string, ModelEntry>();
  const modelsByName = new Map<string, ModelEntry>();
  for (const byApi of Object.values(raw)) {
    if (!byApi || typeof byApi !== "object") continue;
    for (const entry of Object.values(byApi)) {
      if (!entry || typeof entry.id !== "string") continue;
      // "free" models are deliberately excluded: they routinely ship with
      // capabilities cut down, so their numbers describe a reduced product.
      if (/free$/i.test(entry.id)) continue;
      const bare = bareName(entry.id);
      if (!models.has(bare)) models.set(bare, entry);
      if (typeof entry.name === "string") {
        const key = normaliseModelKey(entry.name);
        if (key && !modelsByName.has(key)) modelsByName.set(key, entry);
      }
    }
  }
  return { provider, models, modelsByName };
}

/** The provider's own curated models, by bare name. Read-only, for tests and CLI. */
export function readCuratedIndex(agentDir: string, provider = "opendesign"): Map<string, ModelEntry> {
  try {
    const json = JSON.parse(readFileSync(join(agentDir, "models.json"), "utf8")) as {
      providers?: Record<string, { models?: ModelEntry[] }>;
    };
    const out = new Map<string, ModelEntry>();
    for (const m of json.providers?.[provider]?.models ?? []) {
      if (!m || typeof m.id !== "string") continue;
      const b = bareName(m.id);
      if (!out.has(b)) out.set(b, m);
    }
    return out;
  } catch {
    return new Map();
  }
}

/** Every bundled catalog belonging to an active provider, free ids removed. */
/**
 * Every catalog Pi ships, best donor first.
 *
 * No credential is required and none is asked for: these files are data Pi
 * already installed. OpenRouter leads because it is the primary donor; the rest
 * are corroboration.
 */
export function readPiCatalogs(agentDir: string, options: { exclude?: readonly string[] } = {}): BundledCatalog[] {
  // Never throws. Pi refreshes every provider in one batch, so an exception
  // here aborts the whole batch and leaves every provider on cached models —
  // including the ones that were fine. A donor layer is an enhancement; it is
  // not allowed to take the provider down with it.
  try {
    return readPiCatalogsUnsafe(agentDir, options);
  } catch {
    return [];
  }
}

function readPiCatalogsUnsafe(agentDir: string, options: { exclude?: readonly string[] } = {}): BundledCatalog[] {
  const dir = findBundledCatalogDir(agentDir);
  if (!dir) return [];
  const skip = new Set(options.exclude ?? []);
  let files: string[] = [];
  try {
    files = readdirSync(dir).filter((f) => f.endsWith(".json"));
  } catch {
    return [];
  }
  const out: BundledCatalog[] = [];
  for (const file of files) {
    const provider = file.slice(0, -".json".length);
    if (skip.has(provider)) continue;
    const catalog = readBundledCatalog(dir, provider);
    if (catalog && catalog.models.size) out.push(catalog);
  }
  const rank = (p: string) => {
    const i = PROVIDER_PRIORITY.indexOf(p as (typeof PROVIDER_PRIORITY)[number]);
    return i === -1 ? PROVIDER_PRIORITY.length : i;
  };
  return out.sort((a, b) => rank(a.provider) - rank(b.provider) || a.provider.localeCompare(b.provider));
}

/*
 * An earlier version resolved only the catalogs belonging to providers with a
 * credential, which meant one of them decided alone. That is gone: Pi ships
 * every catalog and reading a file needs no key, so all of them are read and
 * the model name carries the weight instead. The body that used to live here is
 * kept out of the file on purpose — leaving it inside a comment is how it came
 * to be silently disabled in the first place.
 */

// ---------------------------------------------------------------------------
// Resolving one model
// ---------------------------------------------------------------------------

/**
 * Which provider's catalog outranks which. Anything not listed falls after
 * these, in the order they appear in auth.json.
 */
export const PROVIDER_PRIORITY = ["openrouter"] as const;

/**
 * The vendor's own model card, where it is known and a catalog is wrong.
 *
 * This outranks every catalog. A catalog records what a RESELLER believes a
 * model accepts; the card records what the model itself implements. When those
 * disagree the catalog is usually not lying — it is describing the gateway's
 * shape, and the extra values are accepted then ignored, which is worse than
 * not offering them.
 *
 * Empty for now: no model card has been transcribed here yet. Every entry must
 * name the card it came from and say why it exists, so a later reader can check
 * it rather than trust it.
 */
export interface VendorSpec {
  input?: Array<"text" | "image">;
  maxTokens?: number;
  thinkingLevelMap?: Record<string, string | null>;
  why: string;
}

export const VENDOR_SPEC: Record<string, VendorSpec> = {};


export interface Resolved {
  entry: ModelEntry;
  /** The source that supplied the values, if any. */
  source?: string;
  /** Every other provider that also knows this model: corroboration only. */
  corroborating: string[];
  rule: "vendor" | "donated" | "kept" | "corroborated" | "none";
  /** The exact id in the donor catalog that matched, prefix included. */
  matchedId?: string;
}

const withinTolerance = (a: number, b: number) =>
  Math.abs(a - b) <= ROUNDING_TOLERANCE * Math.max(Math.abs(a), Math.abs(b));

/**
 * Resolve one model's values, in strict priority order:
 *
 *     hand-written  >  openrouter  >  the rest of the active providers
 *
 * The first source that knows the model supplies its values. Every other source
 * that knows it is recorded as corroboration — it confirms the model exists and
 * agrees on its structure, but it never overrides a higher source. Nothing is
 * averaged.
 */
/**
 * Where a model's values come from, decided by corroboration.
 *
 * The catalog named after the model's own vendor is consulted first and speaks
 * with the most weight; openrouter is consulted next; every other catalog
 * corroborates. But a field is not settled by rank alone: the value the most
 * catalogs agree on is the one that gets published. Rank is only the tiebreak.
 *
 * That ordering matters less than it looks, because the two agree most of the
 * time. For `deepseek-v4.1-flash`, eight catalogs say `maxTokens: 384000` —
 * the vendor's own first among them — and openrouter alone says 943718. The
 * published ceiling followed openrouter and the endpoint rejected it.
 *
 * A value needs a simple majority of the catalogs that state the field at all.
 * Three votes out of ten is not corroboration, it is a plurality, and a
 * plurality does not overrule the vendor: without a majority the field falls
 * back to the vendor's catalog, then to openrouter.
 *
 * Nothing is averaged. A number nobody published is not a consensus, it is an
 * invention.
 */

/** Fields whose value is a property of THIS endpoint, not of the model. */
export const ENDPOINT_FIELDS = ["contextWindow", "cost", "compat"] as const;

/** Group values so 128_000 and 131_072 count as one number. */
const sameNumber = (a: number, b: number) =>
  Math.abs(a - b) <= ROUNDING_TOLERANCE * Math.max(Math.abs(a), Math.abs(b));

/** Every catalog that knows the model, plus how the match was made. */
export interface CatalogHit {
  provider: string;
  entry: ModelEntry;
  matchedId: string;
  /** Which field carried the match: the id, or the human name. */
  via: "id" | "alias" | "name";
}

/**
 * Find the model in one catalog: exact id first, then a dated alias, then the
 * punctuation-stripped human name.
 */
export function findInCatalog(
  catalog: BundledCatalog,
  bare: string,
  aliases: readonly string[] = [],
): CatalogHit | undefined {
  for (const name of [bare, ...aliases]) {
    const entry = catalog.models.get(name);
    if (entry) {
      return { provider: catalog.provider, entry, matchedId: entry.id, via: name === bare ? "id" : "alias" };
    }
  }
  const byName = catalog.modelsByName?.get(normaliseModelKey(bare));
  if (byName) return { provider: catalog.provider, entry: byName, matchedId: byName.id, via: "name" };
  return undefined;
}

/** What one field resolved to, and who said it. */
export interface FieldResolution {
  value: unknown;
  votes: number;
  total: number;
  how: "majority" | "vendor fallback" | "openrouter fallback";
  providers: string[];
}

/**
 * Decide one field from every catalog that states it.
 *
 * `thinkingLevelMap` is decided key by key: a catalog that omits a level is
 * silent about it, and silence must not erase what another one asserted. An
 * explicit `null` is an assertion and counts as one.
 */
export function resolveByCorroboration(
  hits: readonly CatalogHit[],
  field: string,
  vendorProvider?: string,
  primary?: string,
): FieldResolution | undefined {
  if (field === "thinkingLevelMap") return resolveThinkingLevelMap(hits, primary);

  const bucket = new Map<string, { value: unknown; providers: string[] }>();
  const levelKey = field.startsWith("thinkingLevelMapKey:")
    ? field.slice("thinkingLevelMapKey:".length)
    : undefined;
  for (const hit of hits) {
    const value = levelKey === undefined
      ? hit.entry[field]
      : hit.entry.thinkingLevelMap && Object.prototype.hasOwnProperty.call(hit.entry.thinkingLevelMap, levelKey)
        ? hit.entry.thinkingLevelMap[levelKey]
        : undefined;
    if (value === undefined) continue;
    let key: string;
    if (typeof value === "number") {
      let found: string | undefined;
      for (const existing of bucket.keys()) {
        const prior = bucket.get(existing)!.value;
        if (typeof prior === "number" && sameNumber(prior, value)) {
          found = existing;
          break;
        }
      }
      key = found ?? String(value);
    } else {
      key = JSON.stringify(value);
    }
    if (!bucket.has(key)) bucket.set(key, { value, providers: [] });
    bucket.get(key)!.providers.push(hit.provider);
  }
  if (!bucket.size) return undefined;
  const r = pick(bucket, vendorProvider, primary);
  return {
    value: r.winner.value,
    votes: r.winner.providers.length,
    how: r.how,
    total: [...bucket.values()].reduce((s, b) => s + b.providers.length, 0),
    providers: r.winner.providers,
  };
}

function resolveThinkingLevelMap(hits: readonly CatalogHit[], primary?: string): FieldResolution | undefined {
  const levels = new Set<string>();
  for (const hit of hits) {
    const map = hit.entry.thinkingLevelMap;
    if (map && typeof map === "object") for (const level of Object.keys(map)) levels.add(level);
  }
  if (!levels.size) return undefined;

  const value: Record<string, string | null> = {};
  const winningProviders = new Set<string>();
  let total = 0;
  let usedFallback = false;
  for (const level of levels) {
    // A missing key is silence. Explicit null is a vote.
    const resolution = resolveByCorroboration(hits, `thinkingLevelMapKey:${level}`, undefined, primary);
    if (!resolution) continue;
    value[level] = resolution.value as string | null;
    total += resolution.total;
    for (const provider of resolution.providers) winningProviders.add(provider);
    if (resolution.how !== "majority") usedFallback = true;
  }
  return {
    value,
    votes: winningProviders.size,
    total,
    how: usedFallback ? "openrouter fallback" : "majority",
    providers: [...winningProviders],
  };
}

function pick(
  bucket: Map<string, { value: unknown; providers: string[] }>,
  vendorProvider?: string,
  primary?: string,
): { winner: { value: unknown; providers: string[] }; how: FieldResolution["how"]; total: number } {
  const total = [...bucket.values()].reduce((s, b) => s + b.providers.length, 0);
  const ranked = [...bucket.values()].sort((a, b) => b.providers.length - a.providers.length);
  const best = ranked[0];
  if (best.providers.length * 2 > total) {
    return { winner: best, how: "majority", total };
  }
  // No majority. Rank decides, and the vendor's own catalog outranks the
  // reseller's: a catalog maintained by the vendor records what the model
  // implements, not what one gateway happens to accept.
  if (vendorProvider) {
    const vendor = ranked.find((b) => b.providers.includes(vendorProvider));
    if (vendor) return { winner: vendor, how: "vendor fallback", total };
  }
  if (primary) {
    const res = ranked.find((b) => b.providers.includes(primary));
    if (res) return { winner: res, how: "openrouter fallback", total };
  }
  return { winner: best, how: "majority", total };
}

/**
 * An approximate price, derived from the catalogs — never published.
 *
 * A price is a property of the reseller, not of the model: OpenRouter's price
 * is what OpenRouter charges, and EnClave's is what EnClave charges. Voting on
 * it would produce a number nobody charges, which is why `cost` is absent from
 * BUNDLED_FIELDS and why the published block keeps the endpoint's own figure.
 *
 * What is useful is the SPREAD: the range the model is sold at across every
 * catalog Pi ships. It answers "what order of magnitude is this" honestly,
 * where a single average would answer it falsely. Ask for it explicitly.
 */
export interface CostRange {
  input: { min: number; max: number };
  output: { min: number; max: number };
  /** How many catalogs stated a price at all. */
  from: number;
}

export function estimateCostRange(hits: readonly CatalogHit[]): CostRange | undefined {
  const inputs: number[] = [];
  const outputs: number[] = [];
  for (const hit of hits) {
    const cost = hit.entry.cost;
    if (!cost || typeof cost !== "object") continue;
    if (typeof cost.input === "number") inputs.push(cost.input);
    if (typeof cost.output === "number") outputs.push(cost.output);
  }
  if (!inputs.length && !outputs.length) return undefined;
  const span = (xs: number[]) => (xs.length ? { min: Math.min(...xs), max: Math.max(...xs) } : { min: 0, max: 0 });
  return { input: span(inputs), output: span(outputs), from: hits.length };
}

/**
 * Whether a catalog's figure is a claim the model could actually honour.
 *
 * A ceiling that reaches the model's own declared window is not a statement
 * about output: it leaves no room for the prompt that has to go with it. That
 * is how some catalogs write the row — Moonshot's lists `kimi-k3` with
 * `contextWindow: 1048576` and `maxTokens: 1048576`, both the same number —
 * and publishing it would hand the endpoint an impossibility, which is the one
 * failure mode the clamp below exists to prevent.
 *
 * Such a figure is treated as silence rather than as a claim, so the field
 * falls through to the catalogs that state a ceiling a model can serve.
 */
export function isPossibleValue(entry: ModelEntry, field: string): boolean {
  if (field !== "maxTokens") return true;
  const max = entry.maxTokens;
  const window = entry.contextWindow;
  if (typeof max !== "number" || typeof window !== "number") return true;
  return max < window;
}

export function resolveModel(
  bare: string,
  kept: ModelEntry | undefined,
  bundled: readonly BundledCatalog[],
  isAlias: boolean,
): Resolved {
  // Aliases are left alone: the same bare name is a different thing in a
  // different router, and its catalog numbers would be false here. This is the
  // guard that keeps `auto` out of the corroboration count — with one catalog
  // stating a value, a bare majority would otherwise hand it the field.
  if (isAlias) return { entry: {}, corroborating: [], rule: "none" };

  // The exact name first; a dated vendor slug only when the catalog does not
  // know the short one; the human name last, which is what connects an endpoint
  // that says `deepseek-v4.1-flash` to a vendor catalog that says `deepseek-flash`.
  const aliases = NAME_ALIASES[bare] ?? [];
  const knowing = bundled
    .map((c) => findInCatalog(c, bare, aliases))
    .filter((h): h is CatalogHit => h !== undefined);

  // The primary donor is whichever catalog ranks first in PROVIDER_PRIORITY.
  const primary = bundled.length ? bundled[0].provider : undefined;

  // 1. The vendor's own card, where one exists. Nothing outranks the model
  //    card about the model, and it is not a vote: it is what the model does.
  const spec = VENDOR_SPEC[bare];
  const anyDonor = knowing[0];

  if (spec) {
    const entry: ModelEntry = anyDonor ? copyFields(anyDonor.entry, BUNDLED_FIELDS) : {};
    if (spec.input) entry.input = spec.input;
    if (spec.maxTokens !== undefined) entry.maxTokens = spec.maxTokens;
    if (spec.thinkingLevelMap) entry.thinkingLevelMap = spec.thinkingLevelMap as ThinkingLevelMap;
    if (!anyDonor && kept) for (const f of HAND_FIELDS) if (kept[f] !== undefined) (entry as Record<string, unknown>)[f] = kept[f];
    return {
      entry,
      source: "model card",
      matchedId: anyDonor?.matchedId,
      corroborating: knowing.map((h) => h.provider),
      rule: "vendor",
    };
  }

  // 2. The vendor's own catalog decides outright.
  //
  //    A catalog maintained by the vendor records what the model implements.
  //    A reseller's records what ONE gateway happens to accept, and gateways
  //    disagree: for `deepseek-v4.1-flash` eight catalogs say `maxTokens`
  //    384000 — the vendor's first among them — and OpenRouter alone says
  //    943718, a figure this endpoint rejects outright. So the vendor is not
  //    one vote among many, it is the vote. If it says something the rest
  //    disagree with, its number is still the one that gets published.
  //
  //    Only a model with no first-party catalog in Pi reaches the rule below,
  //    where the value most catalogs agree on is what stands.
  const vendorProvider = vendorCatalogProvider(knowing, bare);
  const official = vendorProvider ? knowing.find((h) => h.provider === vendorProvider) : undefined;
  if (official) {
    // A vendor's explicit value is absolute for that field/key; silence falls
    // through to corroboration. In a reasoning map every key is resolved
    // independently, rather than letting a partial vendor map erase the rest.
    const entry: ModelEntry = {};
    for (const field of BUNDLED_FIELDS) {
      if (field === "thinkingLevelMap") continue;
      if (official.entry[field] !== undefined && isPossibleValue(official.entry, field))
        (entry as Record<string, unknown>)[field] = official.entry[field];
    }
    const rest = knowing.filter((h) => h.provider !== official.provider);
    for (const field of BUNDLED_FIELDS) {
      if (field === "thinkingLevelMap" || entry[field] !== undefined) continue;
      const r = resolveByCorroboration(rest, field, undefined, primary);
      if (r) (entry as Record<string, unknown>)[field] = r.value;
    }
    const levels = new Set<string>();
    for (const hit of knowing) {
      const map = hit.entry.thinkingLevelMap;
      if (map && typeof map === "object") for (const level of Object.keys(map)) levels.add(level);
    }
    if (levels.size) {
      const map: Record<string, string | null> = {};
      for (const level of levels) {
        const officialMap = official.entry.thinkingLevelMap;
        if (officialMap && Object.prototype.hasOwnProperty.call(officialMap, level)) {
          map[level] = officialMap[level];
          continue;
        }
        const r = resolveByCorroboration(rest, `thinkingLevelMapKey:${level}`, undefined, primary);
        if (r) map[level] = r.value as string | null;
      }
      if (Object.keys(map).length) entry.thinkingLevelMap = map as ThinkingLevelMap;
    }
    return {
      entry,
      source: official.provider,
      matchedId: official.matchedId,
      corroborating: knowing.filter((h) => h.provider !== official.provider).map((h) => h.provider),
      rule: knowing.length > 1 ? "corroborated" : "donated",
    };
  }

  // 3. No vendor catalog: the value the most catalogs agree on. A simple
  //    majority of the catalogs that state the field at all. Three votes out of
  //    ten is a plurality, not corroboration, and a plurality does not overrule
  //    the reseller with the strongest claim: without a majority the field
  //    falls back to OpenRouter.
  if (knowing.length) {
    const entry: ModelEntry = {};
    let decided = 0;
    for (const field of BUNDLED_FIELDS) {
      const r = resolveByCorroboration(knowing, field, undefined, primary);
      if (!r) continue;
      (entry as Record<string, unknown>)[field] = r.value;
      decided++;
    }
    if (decided) {
      const corroborating = knowing.map((h) => h.provider);
      return {
        entry,
        source: primary ?? knowing[0].provider,
        matchedId: knowing.find((h) => h.provider === primary)?.matchedId ?? knowing[0].matchedId,
        corroborating,
        rule: corroborating.length > 1 ? "corroborated" : "donated",
      };
    }
  }

  // 4. No catalog states a field: what is already written stands. It may be a
  //    value measured against this endpoint, which no catalog can beat.
  if (kept) {
    return {
      entry: copyFields(kept, HAND_FIELDS),
      source: "models.json",
      corroborating: [],
      rule: "kept",
    };
  }

  return { entry: {}, corroborating: [], rule: "none" };
}

function copyFields(from: ModelEntry, fields: readonly string[]): ModelEntry {
  const out: ModelEntry = {};
  for (const field of fields) {
    if (from[field] !== undefined) (out as Record<string, unknown>)[field] = from[field];
  }
  return out;
}

/**
 * Pi's extension loader treats EVERY `extensions/*.ts` file as an extension
 * factory and reports "does not export a valid factory function" otherwise.
 * This file is a helper imported by `index.ts`, so it needs a no-op default
 * export to load silently beside it.
 */
export default async function opendesignDonorsHelper(): Promise<void> {}

// ---------------------------------------------------------------------------
// Field-wise overlay
// ---------------------------------------------------------------------------

export interface OverlayResult {
  entry: ModelEntry;
  /** The provider that decided the most fields, if any. */
  source?: string;
  /** The exact id that matched, prefix included, so the match is auditable. */
  matchedId?: string;
  /** Catalogs that also know this model. They confirm; they do not override. */
  corroborating: string[];
  /** Fields the primary donor actually changed. */
  applied: string[];
}

/**
 * Overlay a built model with donor values, one FIELD at a time.
 *
 * The precedence is the EnClave one — model card, then openrouter, then the
 * rest of Pi's catalogs — but the application differs, and deliberately so.
 * A donor that states a value overrides what we had. A donor that is SILENT
 * about a field does not: silence is not an opinion, and letting it blank a
 * known value would turn a gap in the catalog into a loss of real data.
 *
 * That is not a softening of the rule, it is what the rule has to mean to be
 * useful. `mimo-v2.6-flash` has seven working reasoning levels and openrouter
 * lists none for it; honoring "openrouter decides" by erasing them would be
 * worse than anything a wrong ceiling could do.
 *
 * Fields a donor never sets: `contextWindow` and `cost` belong to the endpoint,
 * and `compat` describes how one reseller frames reasoning, so it is never
 * inherited.
 */
export function overlayDonors(
  model: ModelEntry,
  bare: string,
  bundled: readonly BundledCatalog[],
): OverlayResult {
  const out: ModelEntry = { ...model };
  const before = new Map<string, unknown>();
  const applied: string[] = [];
  let source: string | undefined;
  let matchedId: string | undefined;

  const note = (field: string) => {
    if (!before.has(field)) before.set(field, JSON.stringify(out[field]));
  };

  const take = (entry: ModelEntry, fields: readonly string[]) => {
    for (const field of fields) {
      const value = entry[field];
      if (value === undefined || value === null) continue; // silence, not a value
      note(field);

      // A thinking map is merged KEY BY KEY. A catalog that declares only
      // `{off: null}` has not claimed anything about the other six levels, and
      // replacing a seven-key map with a one-key one would delete real
      // measurements. `openrouter` lists `kimi-k2.7-code` with a single key and
      // `mimo-v2.6-*` with none at all.
      if (field === "thinkingLevelMap" && typeof value === "object" && value !== null) {
        const merged: Record<string, string | null> = { ...(out.thinkingLevelMap ?? {}) };
        for (const [k, v] of Object.entries(value as Record<string, string | null>)) merged[k] = v;
        (out as Record<string, unknown>).thinkingLevelMap = merged;
      } else {
        (out as Record<string, unknown>)[field] = value;
      }
    }
  };

  // 1. The vendor's model card, if one exists.
  const card = VENDOR_SPEC[bare];
  if (card) {
    take(card as unknown as ModelEntry, [...BUNDLED_FIELDS, "compat"]);
    source = "model card";
  }

  // 2. Everything else comes from the shared rule, so this bridge and its
  //    sibling cannot drift apart: the vendor's own catalog first, then the
  //    value most catalogs agree on, then what is already written. Keeping a
  //    second copy of that logic here is how the two repos started disagreeing
  //    about the same model.
  const resolved = resolveModel(bare, undefined, bundled, false);
  if (Object.keys(resolved.entry).length) {
    take(resolved.entry, BUNDLED_FIELDS);
    source ??= resolved.source;
    matchedId ??= resolved.matchedId;
  }
  const corroborating = resolved.corroborating;

  for (const field of BUNDLED_FIELDS) {
    if (!before.has(field)) continue;
    if (before.get(field) !== JSON.stringify(out[field])) applied.push(field);
  }

  return { entry: out, source, matchedId, corroborating, applied };
}
